import random

BANK_PREFIXES = {
    "STATE BANK OF INDIA": "SBI", "HDFC BANK LTD": "HDF", "ICICI BANK LTD": "ICI",
    "AXIS BANK LTD": "AXS", "BANK OF BARODA": "BOB", "PUNJAB NATIONAL BANK": "PNB",
    "BANK OF INDIA": "BOI", "CANARA BANK": "CAN", "UNION BANK OF INDIA": "UBI",
    "INDIAN BANK": "IDB", "CENTRAL BANK OF INDIA": "CBI", "INDIAN OVERSEAS BANK": "IOB",
    "UCO BANK": "UCO", "PUNJAB AND SIND BANK": "PSB", "BANK OF MAHARASHTRA": "BOM",
    "FEDERAL BANK LTD": "FED", "KOTAK MAHINDRA BANK LTD": "KTK", "YES BANK LTD": "YES",
    "INDUSIND BANK LTD": "IND", "IDFC FIRST BANK LTD": "IDF", "RBL BANK LTD": "RBL",
    "BANDHAN BANK LTD": "BAN", "SOUTH INDIAN BANK": "SIB", "KARUR VYSYA BANK LTD": "KVB",
    "KARNATAKA BANK LTD": "KBL", "JAMMU AND KASHMIR BANK LTD": "JKB",
    "CITY UNION BANK LTD.": "CUB", "DCB BANK LTD": "DCB", "DHANALAXMI BANK LTD": "DLB",
    "NAINITAL BANK LTD": "NTB", "CSB BANK LTD.": "CSB", "TAMILNAD MERCANTILE BANK LTD": "TMB",
    "IDBI BANK LTD": "IDB", "STANDARD CHARTERED BANK LTD": "SCB", "HSBC LTD": "HSB",
    "CITI BANK": "CIT", "DEUTSCHE BANK LTD": "DEU", "DBS INDIA BANK LTD": "DBS",
    "BARCLAYS BANK PLC": "BRC", "BANK OF AMERICA": "BOA",
    "AMERICAN EXPRESS BANKING CORPORATION": "AXP", "WOORI BANK": "WRB",
    "KOOKMIN BANK": "KMB", "KEB HANA BANK": "HNB", "DOHA BANK Q.P.S.C.": "DOH",
    "BANK OF BAHRAIN & KUWAIT B.S.C.": "BBK", "SBM BANK INDIA LTD": "SBM",
    "AU SMALL FINANCE BANK LTD": "AUS", "EQUITAS SMALL FINANCE BANK LTD": "EQB",
    "CAPITAL SMALL FINANCE BANK LTD": "CSF", "ESAF SMALL FINANCE BANK LTD": "ESF",
    "JANA SMALL FINANCE BANK LTD": "JAN", "UJJIVAN SMALL FINANCE BANK LTD": "UJV",
    "UTKARSH SMALL FINANCE BANK LTD": "UTS", "SURYODAY SMALL FINANCE BANK LTD": "SUR",
    "SLICE SMALL FINANCE BANK LTD": "SLI", "UNITY SMALL FINANCE BANK LTD": "UNI",
    "NORTH EAST SMALL FINANCE BANK LTD": "NES", "SHIVALIK SMALL FINANCE BANK LTD": "SHV",
    "AIRTEL PAYMENTS BANK": "AIR", "PAYTM PAYMENTS BANK": "PYT",
    "INDIA POST PAYMENTS BANK": "IPP", "FINO PAYMENTS BANK": "FIN",
    "JIO PAYMENTS BANK ": "JIO", "NSDL PAYMENTS BANK": "NSD",
}

_handcrafted = {
    "STATE BANK OF INDIA": {
        "type": "PSU", "savings_rate": 3.50, "fd_rate_1yr": 6.80,
        "loan_rate_pl": 8.50, "loan_rate_home": 6.90,
        "atm_daily_limit": 50000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 3000, "monthly_fee": 0,
        "digital_rating": 4.2, "cc_interest": 42.0, "cashback_rate": 0.5,
        "overdraft_limit": 25000, "has_minor_account": True,
        "minor_limit": 2000, "minor_savings_rate": 4.50,
        "branch_count": 62000, "tagline": "The Nation's Bank — Trusted by Millions",
        "strengths": ["Widest branch network", "Lowest loan rates", "Govt backing"],
        "weaknesses": ["Slow digital", "Long queues", "Legacy systems"],
    },
    "HDFC BANK LTD": {
        "type": "PVT", "savings_rate": 3.00, "fd_rate_1yr": 7.00,
        "loan_rate_pl": 11.00, "loan_rate_home": 8.50,
        "atm_daily_limit": 100000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 10000, "monthly_fee": 200,
        "digital_rating": 4.8, "cc_interest": 36.0, "cashback_rate": 1.0,
        "overdraft_limit": 50000, "has_minor_account": True,
        "minor_limit": 2500, "minor_savings_rate": 3.50,
        "branch_count": 15000, "tagline": "We Understand Your World",
        "strengths": ["Best digital", "Premium service", "High ATM limit"],
        "weaknesses": ["High min balance", "Expensive loans", "Service charges"],
    },
    "ICICI BANK LTD": {
        "type": "PVT", "savings_rate": 3.25, "fd_rate_1yr": 6.90,
        "loan_rate_pl": 10.75, "loan_rate_home": 8.25,
        "atm_daily_limit": 75000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 5000, "monthly_fee": 175,
        "digital_rating": 4.6, "cc_interest": 38.0, "cashback_rate": 0.8,
        "overdraft_limit": 40000, "has_minor_account": True,
        "minor_limit": 2000, "minor_savings_rate": 4.00,
        "branch_count": 12000, "tagline": "Khayal Rakhna — We Care",
        "strengths": ["Great digital", "Good service", "Kids account program"],
        "weaknesses": ["Moderate fees", "Crowded branches"],
    },
    "AXIS BANK LTD": {
        "type": "PVT", "savings_rate": 3.10, "fd_rate_1yr": 6.85,
        "loan_rate_pl": 12.00, "loan_rate_home": 8.75,
        "atm_daily_limit": 75000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 5000, "monthly_fee": 150,
        "digital_rating": 4.5, "cc_interest": 40.0, "cashback_rate": 0.75,
        "overdraft_limit": 35000, "has_minor_account": True,
        "minor_limit": 2000, "minor_savings_rate": 3.75,
        "branch_count": 8000, "tagline": "Badhte Raho — Keep Growing",
        "strengths": ["Innovative products", "Good digital", "Young customer focus"],
        "weaknesses": ["Average loan rates", "Branch network limited"],
    },
    "KOTAK MAHINDRA BANK LTD": {
        "type": "PVT", "savings_rate": 4.00, "fd_rate_1yr": 7.25,
        "loan_rate_pl": 10.00, "loan_rate_home": 8.00,
        "atm_daily_limit": 25000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 2000, "monthly_fee": 100,
        "digital_rating": 4.7, "cc_interest": 36.0, "cashback_rate": 1.2,
        "overdraft_limit": 30000, "has_minor_account": True,
        "minor_limit": 5000, "minor_savings_rate": 5.00,
        "branch_count": 5000, "tagline": "Let's Make Money Simple",
        "strengths": ["Highest savings rate", "Best for minors", "Innovative digital"],
        "weaknesses": ["Low ATM limit", "Small branch network"],
    },
    "YES BANK LTD": {
        "type": "PVT", "savings_rate": 3.75, "fd_rate_1yr": 7.10,
        "loan_rate_pl": 12.50, "loan_rate_home": 9.00,
        "atm_daily_limit": 50000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 5000, "monthly_fee": 125,
        "digital_rating": 3.8, "cc_interest": 42.0, "cashback_rate": 0.6,
        "overdraft_limit": 20000, "has_minor_account": False,
        "minor_limit": 0, "minor_savings_rate": 0,
        "branch_count": 2000, "tagline": "Building India's Best Bank",
        "strengths": ["High savings rate", "Business banking"],
        "weaknesses": ["Past instability", "Limited branches"],
    },
    "BANK OF BARODA": {
        "type": "PSU", "savings_rate": 3.35, "fd_rate_1yr": 6.75,
        "loan_rate_pl": 9.50, "loan_rate_home": 7.25,
        "atm_daily_limit": 50000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 2000, "monthly_fee": 0,
        "digital_rating": 4.0, "cc_interest": 44.0, "cashback_rate": 0.4,
        "overdraft_limit": 20000, "has_minor_account": True,
        "minor_limit": 1500, "minor_savings_rate": 4.25,
        "branch_count": 22000, "tagline": "India's International Bank",
        "strengths": ["International presence", "Good rates", "Wide network"],
        "weaknesses": ["Digital lagging", "Slow processes"],
    },
    "PUNJAB NATIONAL BANK": {
        "type": "PSU", "savings_rate": 3.25, "fd_rate_1yr": 6.70,
        "loan_rate_pl": 9.75, "loan_rate_home": 7.10,
        "atm_daily_limit": 35000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 2000, "monthly_fee": 0,
        "digital_rating": 3.6, "cc_interest": 44.0, "cashback_rate": 0.3,
        "overdraft_limit": 15000, "has_minor_account": True,
        "minor_limit": 1000, "minor_savings_rate": 4.00,
        "branch_count": 18000, "tagline": "The Name You Can Bank Upon",
        "strengths": ["Pan-India network", "Low fees"],
        "weaknesses": ["Digital needs improvement", "Past fraud issues"],
    },
    "BANK OF INDIA": {
        "type": "PSU", "savings_rate": 3.20, "fd_rate_1yr": 6.65,
        "loan_rate_pl": 9.25, "loan_rate_home": 7.00,
        "atm_daily_limit": 35000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 1500, "monthly_fee": 0,
        "digital_rating": 3.5, "cc_interest": 45.0, "cashback_rate": 0.3,
        "overdraft_limit": 15000, "has_minor_account": True,
        "minor_limit": 1000, "minor_savings_rate": 4.00,
        "branch_count": 10000, "tagline": "Relationships Beyond Banking",
        "strengths": ["Customer friendly", "Rural reach"],
        "weaknesses": ["Average digital", "Slow service"],
    },
    "CANARA BANK": {
        "type": "PSU", "savings_rate": 3.30, "fd_rate_1yr": 6.75,
        "loan_rate_pl": 9.50, "loan_rate_home": 7.20,
        "atm_daily_limit": 35000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 2000, "monthly_fee": 0,
        "digital_rating": 3.8, "cc_interest": 43.0, "cashback_rate": 0.4,
        "overdraft_limit": 15000, "has_minor_account": True,
        "minor_limit": 1500, "minor_savings_rate": 4.10,
        "branch_count": 14000, "tagline": "Together We Can",
        "strengths": ["Pan-India presence", "Good rural banking"],
        "weaknesses": ["Digital average", "Moderate service"],
    },
    "FEDERAL BANK LTD": {
        "type": "PVT", "savings_rate": 3.40, "fd_rate_1yr": 6.95,
        "loan_rate_pl": 11.50, "loan_rate_home": 8.50,
        "atm_daily_limit": 50000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 5000, "monthly_fee": 0,
        "digital_rating": 4.4, "cc_interest": 40.0, "cashback_rate": 0.7,
        "overdraft_limit": 25000, "has_minor_account": True,
        "minor_limit": 2000, "minor_savings_rate": 3.75,
        "branch_count": 4000, "tagline": "Your Perfect Banking Partner",
        "strengths": ["Excellent digital", "Good service", "Strong in South"],
        "weaknesses": ["Regional concentration", "Limited metro presence"],
    },
    "INDUSIND BANK LTD": {
        "type": "PVT", "savings_rate": 3.15, "fd_rate_1yr": 6.85,
        "loan_rate_pl": 12.00, "loan_rate_home": 8.75,
        "atm_daily_limit": 50000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 5000, "monthly_fee": 150,
        "digital_rating": 4.3, "cc_interest": 38.0, "cashback_rate": 0.8,
        "overdraft_limit": 30000, "has_minor_account": False,
        "minor_limit": 0, "minor_savings_rate": 0,
        "branch_count": 3000, "tagline": "We Make You Feel Richer",
        "strengths": ["Premium banking", "Good wealth management"],
        "weaknesses": ["Expensive", "Limited branches"],
    },
    "IDFC FIRST BANK LTD": {
        "type": "PVT", "savings_rate": 3.50, "fd_rate_1yr": 7.15,
        "loan_rate_pl": 10.50, "loan_rate_home": 8.00,
        "atm_daily_limit": 50000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 2500, "monthly_fee": 0,
        "digital_rating": 4.5, "cc_interest": 36.0, "cashback_rate": 1.0,
        "overdraft_limit": 25000, "has_minor_account": True,
        "minor_limit": 2000, "minor_savings_rate": 4.00,
        "branch_count": 2000, "tagline": "Always You First",
        "strengths": ["No hidden fees", "Good rates", "Transparent"],
        "weaknesses": ["Newer bank", "Growing network"],
    },
    "RBL BANK LTD": {
        "type": "PVT", "savings_rate": 3.25, "fd_rate_1yr": 6.90,
        "loan_rate_pl": 12.50, "loan_rate_home": 9.00,
        "atm_daily_limit": 50000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 5000, "monthly_fee": 150,
        "digital_rating": 4.1, "cc_interest": 40.0, "cashback_rate": 0.6,
        "overdraft_limit": 20000, "has_minor_account": False,
        "minor_limit": 0, "minor_savings_rate": 0,
        "branch_count": 1500, "tagline": "Smart Banking for Smart People",
        "strengths": ["Innovative products", "Good digital"],
        "weaknesses": ["Limited branches", "High fees"],
    },
    "BANDHAN BANK LTD": {
        "type": "PVT", "savings_rate": 3.60, "fd_rate_1yr": 7.00,
        "loan_rate_pl": 11.00, "loan_rate_home": 8.25,
        "atm_daily_limit": 25000, "atm_fee_own": 0, "atm_fee_other": 21,
        "min_balance": 2500, "monthly_fee": 0,
        "digital_rating": 3.9, "cc_interest": 42.0, "cashback_rate": 0.5,
        "overdraft_limit": 15000, "has_minor_account": False,
        "minor_limit": 0, "minor_savings_rate": 0,
        "branch_count": 6000, "tagline": "Banking for Everyone",
        "strengths": ["Strong rural presence", "Microfinance roots"],
        "weaknesses": ["Limited urban presence", "Average digital"],
    },
}

def _generate_attrs(bank_name, bank_type):
    base = {}
    if bank_type == "PSU":
        base = {
            "savings_rate": round(random.uniform(3.0, 3.75), 2),
            "fd_rate_1yr": round(random.uniform(6.5, 7.0), 2),
            "loan_rate_pl": round(random.uniform(8.5, 11.0), 2),
            "loan_rate_home": round(random.uniform(6.75, 7.5), 2),
            "atm_daily_limit": random.choice([25000, 35000, 50000]),
            "atm_fee_own": 0, "atm_fee_other": 21,
            "min_balance": random.choice([1000, 2000, 3000, 5000]),
            "monthly_fee": 0,
            "digital_rating": round(random.uniform(3.0, 4.2), 1),
            "cc_interest": round(random.uniform(42, 46), 1),
            "cashback_rate": round(random.uniform(0.2, 0.5), 1),
            "overdraft_limit": random.choice([10000, 15000, 20000, 25000]),
            "has_minor_account": True,
            "minor_limit": random.choice([1000, 1500, 2000]),
            "minor_savings_rate": round(random.uniform(3.75, 4.5), 2),
        }
    elif bank_type == "PVT":
        base = {
            "savings_rate": round(random.uniform(2.75, 3.75), 2),
            "fd_rate_1yr": round(random.uniform(6.75, 7.25), 2),
            "loan_rate_pl": round(random.uniform(10.0, 14.0), 2),
            "loan_rate_home": round(random.uniform(7.75, 9.5), 2),
            "atm_daily_limit": random.choice([50000, 75000, 100000]),
            "atm_fee_own": 0, "atm_fee_other": 21,
            "min_balance": random.choice([5000, 10000, 25000]),
            "monthly_fee": random.choice([0, 100, 150, 200]),
            "digital_rating": round(random.uniform(3.8, 5.0), 1),
            "cc_interest": round(random.uniform(36, 42), 1),
            "cashback_rate": round(random.uniform(0.5, 1.5), 1),
            "overdraft_limit": random.choice([15000, 25000, 35000, 50000]),
            "has_minor_account": random.choice([True, True, False]),
            "minor_limit": 2000 if random.random() > 0.3 else 2500,
            "minor_savings_rate": round(random.uniform(3.5, 4.5), 2),
        }
    elif bank_type == "FOREIGN":
        base = {
            "savings_rate": round(random.uniform(2.5, 3.25), 2),
            "fd_rate_1yr": round(random.uniform(6.0, 6.75), 2),
            "loan_rate_pl": round(random.uniform(12.0, 16.0), 2),
            "loan_rate_home": round(random.uniform(9.0, 11.0), 2),
            "atm_daily_limit": random.choice([75000, 100000, 150000, 200000]),
            "atm_fee_own": 0, "atm_fee_other": 21,
            "min_balance": random.choice([10000, 25000, 50000, 100000]),
            "monthly_fee": random.choice([0, 200, 350, 500]),
            "digital_rating": round(random.uniform(4.0, 5.0), 1),
            "cc_interest": round(random.uniform(30, 38), 1),
            "cashback_rate": round(random.uniform(1.0, 2.5), 1),
            "overdraft_limit": random.choice([50000, 100000, 200000]),
            "has_minor_account": False,
            "minor_limit": 0, "minor_savings_rate": 0,
        }
    elif bank_type == "SFB":
        base = {
            "savings_rate": round(random.uniform(4.0, 7.5), 2),
            "fd_rate_1yr": round(random.uniform(7.0, 8.5), 2),
            "loan_rate_pl": round(random.uniform(12.0, 18.0), 2),
            "loan_rate_home": round(random.uniform(9.0, 12.0), 2),
            "atm_daily_limit": random.choice([10000, 15000, 25000]),
            "atm_fee_own": 0, "atm_fee_other": 21,
            "min_balance": random.choice([0, 1000, 2000, 2500]),
            "monthly_fee": 0,
            "digital_rating": round(random.uniform(3.5, 4.5), 1),
            "cc_interest": round(random.uniform(38, 44), 1),
            "cashback_rate": round(random.uniform(0.3, 0.8), 1),
            "overdraft_limit": random.choice([5000, 10000, 15000]),
            "has_minor_account": True,
            "minor_limit": 1000,
            "minor_savings_rate": round(random.uniform(5.0, 7.5), 2),
        }
    elif bank_type == "PAYMENTS":
        base = {
            "savings_rate": round(random.uniform(3.0, 4.0), 2),
            "fd_rate_1yr": 0, "loan_rate_pl": 0, "loan_rate_home": 0,
            "atm_daily_limit": random.choice([10000, 15000, 25000]),
            "atm_fee_own": 0, "atm_fee_other": 0,
            "min_balance": 0, "monthly_fee": 0,
            "digital_rating": round(random.uniform(4.3, 5.0), 1),
            "cc_interest": 0, "cashback_rate": round(random.uniform(0.5, 2.0), 1),
            "overdraft_limit": 0, "has_minor_account": False,
            "minor_limit": 0, "minor_savings_rate": 0,
        }
    base["type"] = bank_type
    return base

def get_bank_attrs(bank_name):
    from src.utils import get_bank_type as gbt
    key = bank_name.strip().upper()
    if key in _handcrafted:
        return _handcrafted[key]
    bt = gbt(key)
    if bt == "OTHER":
        bt = "PVT"
    return _generate_attrs(key, bt)

def get_bank_prefix(bank_name):
    key = bank_name.strip().upper()
    return BANK_PREFIXES.get(key, key[:4])

def get_all_bank_prefixes():
    return dict(BANK_PREFIXES)
